workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

stages:
  - prepare
  - static
  - test

variables:
  CI_PHP_IMAGE: "registry.gzcrm.cn/php-group/ci-dockerfile:v0.1.10-php8.4"
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer-cache"

default:
  interruptible: true
  cache:
    - key:
        files:
          - composer.json
        prefix: "composer-cache"
      paths:
        - .composer-cache/
      policy: pull

deps:
  stage: prepare
  image: "$CI_PHP_IMAGE"
  cache:
    - key:
        files:
          - composer.json
        prefix: "composer-cache"
      paths:
        - .composer-cache/
      policy: pull-push
  before_script:
    - php -v
    - composer --version
  script:
    - composer validate
    - composer-install
  artifacts:
    name: "vendor-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"
    expire_in: 8h
    paths:
      - vendor/
      - composer.lock

phpstan:
  stage: static
  image: "$CI_PHP_IMAGE"
  needs:
    - job: deps
      artifacts: true
  script:
    - php -v
    - ./vendor/bin/phpstan analyse src tests --level=5 --memory-limit=2G

phpunit:
  stage: test
  image: "$CI_PHP_IMAGE"
  needs:
    - job: deps
      artifacts: true
  script:
    - redis-start
    - php -v
    - ./vendor/bin/phpunit tests
